"""Community skill sharing via a GitHub-hosted registry.

The registry is just a regular git repo with:

    skills/<category>/<skill-name>/SKILL.md
    index.json   (auto-generated by CI, lists all skills with checksums)

Anyone can fork to run a private registry — `sf registry set <url>` switches.

This module ships:
  - manifest.py        build/parse index.json
  - github_sync.py     fetch index + skills from a registry URL
  - (no auth required for fetch; publish uses `gh` CLI for PRs)
"""

from .manifest import build_index, load_index, IndexEntry
from .github_sync import fetch_index, install_skill, registry_url

__all__ = [
    "build_index", "load_index", "IndexEntry",
    "fetch_index", "install_skill", "registry_url",
]
